name: Publish specific artifacts
on:
  push:
    branches: ['develop']
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v3
      - name: Setup Java / Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Publish snapshot package
        uses: ./.github/workflows/publish.yaml
