name: Release and Tag
on: ['workflow_dispatch']
jobs:
  cut-and-tag:
    name: Release and Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout develop
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'develop'
      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Setup Java / Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Release package
        run: |
          mvn --batch-mode \
            -DgitFlowConfig.productionBranch=main \
            -DversionDigitToIncrement=1 \
            -DpostReleaseGoals=deploy \
            -DargLine="-DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }}" \
            clean \
            com.amashchenko.maven.plugin:gitflow-maven-plugin:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
