name: Cut and tag release
on: ['workflow_dispatch']
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout develop
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'develop'
      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Setup Java / Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Release package
        run: mvn --batch-mode clean com.amashchenko.maven.plugin:gitflow-maven-plugin:release-start com.amashchenko.maven.plugin:gitflow-maven-plugin:release-finish -DgitFlowConfig.productionBranch=main -DversionDigitToIncrement=1
      - name: Trigger CI
        uses: ./.github/workflows/ci-specific.yaml
        with:
          branch: main
      - name: Trigger CI
        uses: ./.github/workflows/ci-specific.yaml
        with:
          branch: develop
