name: Publish package to GitHub Packages
on: ['workflow_dispatch']
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Checkout develop
        uses: actions/checkout@v3
        with:
          ref: 'refs/heads/develop'
      - name: Release package
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mvn --batch-mode \
            clean \
            com.amashchenko.maven.plugin:gitflow-maven-plugin:release-start \
            deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }} \
            com.amashchenko.maven.plugin:gitflow-maven-plugin:release-finish -DgitFlowConfig.productionBranch=main -DversionDigitToIncrement=1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
